
CREATE SCHEMA IF NOT EXISTS `talaria_seller`;

USE `talaria_seller`;

CREATE TABLE IF NOT EXISTS `seller` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `code` varchar(20) NOT NULL,
    `name` varchar(255) DEFAULT NULL,
    `tax_code` varchar(255) DEFAULT NULL,
    `tax_name` varchar(255) DEFAULT NULL,
    `tax_address` varchar(255) DEFAULT NULL,
    `logo` varchar(255) DEFAULT NULL,
    `logo_printing` varchar(255) DEFAULT NULL,
    `hotline` varchar(255) DEFAULT NULL,
    `website_url` varchar(255) DEFAULT NULL,
    `email` varchar(255) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` varchar(32) DEFAULT NULL,
    `updated_by` varchar(32) DEFAULT NULL,
    `status` tinyint(1) DEFAULT '1',
    `contract_code` varchar(255) DEFAULT NULL,
    `inventory_type` varchar(255) DEFAULT NULL,
    `kam_id` int(10) unsigned DEFAULT NULL,
    `kam_email` varchar(255) DEFAULT NULL,
    `kam_name` varchar(255) DEFAULT NULL,
    `kam_phone` varchar(255) DEFAULT NULL,
    `installment_status` tinyint(1) DEFAULT '0',
    `is_cross_border` tinyint(1) DEFAULT '0',
    `secret` varchar(255) DEFAULT '',
    `connect_to` varchar(25) DEFAULT '',
    `ref_id` varchar(25) DEFAULT '',
    `product_is_sync` tinyint(4) DEFAULT '0',
    `integration_status` tinyint(4) DEFAULT '0',
    `seller_channel` varchar(255) DEFAULT '',
    `is_all_vat_supported` tinyint(1) DEFAULT '0',
    `vat_limit_supported` float DEFAULT '0',
    `backorder_pickup_method` varchar(100) DEFAULT NULL,
    `webhook_url` varchar(255) DEFAULT NULL,
    `evoucher_issuer` varchar(255) DEFAULT NULL,
    `live_at` timestamp NULL DEFAULT NULL,
    `live_by` varchar(100) DEFAULT NULL,
    `extra_fee` varchar(255) DEFAULT NULL,
    `redeem_evoucher` tinyint(1) DEFAULT '1',
    `email_contract` varchar(255) DEFAULT NULL,
    `phone_contract` varchar(16) DEFAULT NULL,
    `id_authoring` varchar(64) DEFAULT NULL,
    `business_representative_contract` varchar(255) DEFAULT NULL,
    `referenced_from` varchar(255) DEFAULT NULL,
    `type_channel` varchar(32) DEFAULT NULL,
    `note` varchar(512) DEFAULT NULL,
    `reason` varchar(255) DEFAULT NULL,
    `return_ware_area` varchar(255) DEFAULT NULL,
    `warehouse_address_province_expectation` varchar(100) DEFAULT NULL,
    `config` text,
    `seller_delivery_model` varchar(100) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `seller_code_unique` (`code`),
    UNIQUE KEY `seller_name_unique` (`name`),
    UNIQUE KEY `seller_contract_code_unique` (`contract_code`),
    KEY `seller_id_code_name_index` (`id`,`code`,`name`),
    KEY `seller_backorder_pickup_method` (`backorder_pickup_method`) USING BTREE,
    KEY `IDX_TAX_CODE` (`tax_code`) USING BTREE,
    KEY `IDX_KAM_EMAIL` (`kam_email`) USING BTREE,
    KEY `secret_idx` (`secret`)
);